version: 2.1

orbs:
  slack: circleci/slack@1.0.0
  rollbar: rollbar/deploy@1.0.1

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10

    steps:
      - checkout

      - restore_cache:
          key: yarn-v2-{{ checksum "yarn.lock" }}-{{ arch }}

      - restore_cache:
          key: node-v2-{{ checksum "package.json" }}-{{ arch }}

      - run: yarn install

      - save_cache:
          key: yarn-v2-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn

      - save_cache:
          key: node-v2-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

      - run:
          name: Run linting
          command: |
            yarn lint

      - run:
          name: Run Typescript compilation
          command: yarn tsc --skipLibCheck --noEmit

  deploy:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10
    steps:
      - checkout

      - restore_cache:
          key: yarn-v2-{{ checksum "yarn.lock" }}-{{ arch }}

      - restore_cache:
          key: node-v2-{{ checksum "package.json" }}-{{ arch }}

      - run: yarn install

      - save_cache:
          key: yarn-v2-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn

      - save_cache:
          key: node-v2-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

      - run:
          name: Serverless deploy to production
          command: yarn serverless deploy -v --stage prod
      - rollbar/notify_deploy:
          environment: "production"

workflows:
  version: 2
  built_test_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
