dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.4.0
  - aave/protocol-v2@1.0.1
compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.4.0"
      - "@aave=aave/protocol-v2@1.0.1"
networks:
  default: mainnet-fork-dev
  kovan:
    weth_token: "0xd0A1E359811322d97991E03f863a0C30C2cF029C"
    lending_pool_addresses_provider: "0x88757f2f99175387aB4C6a4b3067c77A695b0349"
    aave_dai_token: "0x4F96Fe3b7A6Cf9725f59d353F723c1bDb64CA6Aa"
  mainnet-fork-dev:
    weth_token: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
    lending_pool_addresses_provider: "0xB53C1a33016B2DC2fF3653530bfF1848a515c8c5"
    aave_dai_token: "0x6B175474E89094C44Da98b954EedeAC495271d0F"
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
