[tool.black]
line-length = 79
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | \.serverless
  | _build
  | buck-out
  | build
  | dist
  | node_modules
  | static
  | scripts

  # The following are specific to Black, you probably don't want those.
  | blib2to3
  | tests/data
)/
'''
include = '.*\.pyi?$'
