# Generated by Django 2.1.5 on 2019-01-30 17:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "data",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        default=dict
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("logged_at", models.DateTimeField()),
                (
                    "client_id",
                    models.TextField(blank=True, db_index=True, null=True),
                ),
                ("activity_type", models.TextField(db_index=True)),
                ("activity_key", models.TextField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name="AppUser",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                (
                    "data",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        default=dict
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                (
                    "data",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        default=dict
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="activity",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="advocate.Device",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="advocate.AppUser",
            ),
        ),
    ]
