# Generated by Django 2.1.5 on 2019-01-30 17:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [("advocate", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="client_id",
            field=models.TextField(
                blank=True, db_index=True, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
