# Generated by Django 2.1.5 on 2019-03-04 12:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("advocate", "0002_auto_20190130_1738")]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="device_data",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="activity",
            name="user_data",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
