# Generated by Django 2.1.5 on 2019-03-06 16:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [("advocate", "0003_auto_20190304_1258")]

    operations = [
        migrations.CreateModel(
            name="DeliveredSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("user_email", models.TextField(db_index=True)),
                ("session_id", models.TextField(db_index=True)),
                ("session_start", models.DateTimeField()),
                ("session_end", models.DateTimeField()),
                (
                    "participants",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        default=dict
                    ),
                ),
                (
                    "participants_count",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "extra",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        default=dict
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        )
    ]
