# Generated by Django 2.1.5 on 2019-05-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("advocate", "0004_deliveredsession")]

    operations = [
        migrations.CreateModel(
            name="BookedActivationSession",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_email", models.CharField(max_length=250)),
                ("programme_id", models.IntegerField()),
                ("booked_at", models.DateTimeField()),
                ("available_from", models.DateTimeField()),
                ("booking_url", models.URLField(blank=True, null=True)),
                ("booking_message", models.CharField(max_length=140)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="bookedactivationsession",
            unique_together={("user_email", "programme_id")},
        ),
    ]
