# Generated by Django 2.1.5 on 2019-05-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("advocate", "0005_auto_20190522_1308")]

    operations = [
        migrations.CreateModel(
            name="ProgrammeActivationOptions",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("programme_id", models.IntegerField(unique=True)),
                ("enabled", models.BooleanField()),
                ("request_message", models.CharField(max_length=140)),
                ("request_url", models.URLField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        )
    ]
