# Generated by Django 2.1.5 on 2019-05-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("advocate", "0006_programmeactivationoptions")]

    operations = [
        migrations.AlterField(
            model_name="bookedactivationsession",
            name="available_from",
            field=models.DateTimeField(
                help_text="When is the user first able to join/attend the session (e.g. join a remote call from the app)?"
            ),
        ),
        migrations.AlterField(
            model_name="bookedactivationsession",
            name="booked_at",
            field=models.DateTimeField(
                help_text="When is the activation session booked for?"
            ),
        ),
        migrations.AlterField(
            model_name="bookedactivationsession",
            name="booking_message",
            field=models.CharField(
                help_text="Message presented to users who wish to join/attend their activation session",
                max_length=140,
            ),
        ),
        migrations.AlterField(
            model_name="bookedactivationsession",
            name="booking_url",
            field=models.URLField(
                blank=True,
                help_text="Optional URL used for the user to attend their activation session (e.g. a web conferencing link)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="programmeactivationoptions",
            name="request_message",
            field=models.CharField(
                help_text="Message presented to users who wish to book an activation session",
                max_length=140,
            ),
        ),
        migrations.AlterField(
            model_name="programmeactivationoptions",
            name="request_url",
            field=models.URLField(
                blank=True,
                help_text="Optional URL that users booking an activation session should be sent to",
                null=True,
            ),
        ),
    ]
