# Generated by Django 2.1.5 on 2019-05-23 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("advocate", "0007_auto_20190522_1548")]

    operations = [
        migrations.RemoveField(
            model_name="bookedactivationsession", name="available_from"
        )
    ]
