# Generated by Django 2.1.5 on 2019-05-23 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("advocate", "0008_remove_bookedactivationsession_available_from")
    ]

    operations = [
        migrations.RenameField(
            "BookedActivationSession", "booked_at", "booking_starts"
        )
    ]
