# Generated by Django 2.1.5 on 2019-06-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("advocate", "0009_auto_20190523_0956")]

    operations = [
        migrations.AddField(
            model_name="deliveredsession",
            name="client_id",
            field=models.TextField(
                blank=True, db_index=True, null=True, unique=True
            ),
        )
    ]
