# Generated by Django 2.1.5 on 2019-06-17 13:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [("advocate", "0010_deliveredsession_client_id")]

    operations = [
        migrations.CreateModel(
            name="CoachCall",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("programme_id", models.IntegerField(db_index=True)),
                (
                    "call_starts",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When is the activation session booked for?",
                    ),
                ),
                (
                    "call_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional URL used for the user to attend their activation session (e.g. a web conferencing link)",
                        null=True,
                    ),
                ),
                (
                    "call_message",
                    models.CharField(
                        help_text="Message presented to users who wish to join/attend their activation session",
                        max_length=140,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="programmeactivationoptions",
            name="use_coach_calls",
            field=models.BooleanField(default=False),
        ),
    ]
