# Generated by Django 2.1.5 on 2019-06-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("advocate", "0011_auto_20190617_1358")]

    operations = [
        migrations.AlterField(
            model_name="coachcall",
            name="call_message",
            field=models.CharField(
                help_text="Message presented to users who wish to join/attend their calls",
                max_length=140,
            ),
        ),
        migrations.AlterField(
            model_name="coachcall",
            name="call_starts",
            field=models.DateTimeField(
                db_index=True, help_text="When is the calls booked for?"
            ),
        ),
        migrations.AlterField(
            model_name="coachcall",
            name="call_url",
            field=models.URLField(
                blank=True,
                help_text="Optional URL used for the user to attend their calls (e.g. a web conferencing link)",
                null=True,
            ),
        ),
    ]
