// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-east-2",
  aws_cognito_identity_pool_id:
    "us-east-2:4d5ff0a4-4864-4c0f-bf53-1e2f02563b09",
  aws_cognito_region: "us-east-2",
  aws_mobile_analytics_app_id: "90af754dc8d94db4aaedd88d11f1a716",
  aws_mobile_analytics_app_region: "us-east-1"
};

export default awsmobile;
