
service: advocate-booked-activations

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  environment:
    CALENDLY_WEBHOOK_SECRET: ${env:CALENDLY_WEBHOOK_SECRET}
    CALENDLY_WEBHOOK_SUBSCRIPTION_ID: ${env:CALENDLY_WEBHOOK_SUBSCRIPTION_ID}

functions:
  syncCalendlyDatas:
    handler: handler.syncCalendlyDatas
    events:
      - http:
          path: webhook
          method: post
          cors: true
          integration: lambda-proxy

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack